[project]
name = "ex0928"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SeoungjinPark", email = "sjjw1111@naver.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "faiss-cpu",
    "langchain",
    "langchain-community",
    "langchain-openai",
    "langchain-teddynote",
    "pypdf",
    "python-dotenv",
]

[project.scripts]
ex0928 = "ex0928:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
